apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: myapp-client
          image: jji421/myapp-client:latest
          ports:
            - containerPort: 3000
