apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: "myapp-server-cluster-ip-service"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - junwonjang.dev
        - www.junwonjang.dev
      secretName: junwonjang-dev
  rules:
    - host: junwonjang.dev
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: myapp-client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: myapp-server-cluster-ip-service
              servicePort: 5000
    - host: www.junwonjang.dev
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: myapp-client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: myapp-server-cluster-ip-service
              servicePort: 5000
